In [14]:
import pandas as pd

df_movies = pd.read_csv('C:/Users/pwbry/OneDrive/Desktop/Documents/Projects/MovieRecAPI/ml-latest-small/movies.csv')
df_ratings = pd.read_csv('C:/Users/pwbry/OneDrive/Desktop/Documents/Projects/MovieRecAPI/ml-latest-small/ratings.csv')
df_merged = pd.merge(df_movies, df_ratings, on='movieId', how='inner')
df_merged.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483

 Create a dataframe which maps individual user ratings into rows against each movie as a column and drop movies that had fewer than 8 ratings.

In [15]:
df = df_merged.pivot_table(index='userId', columns='title', values='rating')
# Keep only movies that had at least 8 ratings
df = df.dropna(thresh=8, axis=1)
df.fillna(0, inplace=True)
df.head()

title,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),102 Dalmatians (2000),12 Angry Men (1957),12 Years a Slave (2013),...,Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),[REC] (2007),eXistenZ (1999),xXx (2002),Â¡Three Amigos! (1986)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Uses the Pearson correlation to calculate the similarity between movies!

The Pearson method treats each movie (i.e. column) as a vector containing user rating values and determines how close/similar a movie is to the other ones.

In [16]:
df_similarity = df.corr(method='pearson')
#Store the data for later to be used in building the API
df_similarity.to_csv('movie_similarity.csv')
df_similarity.head()

title,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),102 Dalmatians (2000),12 Angry Men (1957),12 Years a Slave (2013),...,Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),[REC] (2007),eXistenZ (1999),xXx (2002),Â¡Three Amigos! (1986)
title,,,,,,,,,,,,,,,,,,,,,
"'burbs, The (1989)",1.000000,0.063117,-0.023768,0.143482,0.011998,0.087931,0.224052,-0.018608,0.034223,0.009277,...,0.032470,0.134701,0.153158,0.101301,0.049897,0.003233,-0.017905,0.187953,0.062174,0.353194
(500) Days of Summer (2009),0.063117,1.000000,0.142471,0.273989,0.193960,0.148903,0.142141,0.066567,0.159756,0.135486,...,0.178655,0.068407,0.414585,0.355723,0.252226,0.216007,0.126147,0.053614,0.241092,0.125905
10 Cloverfield Lane (2016),-0.023768,0.142471,1.000000,-0.005799,0.112396,0.006139,-0.016835,-0.017692,0.031704,-0.024275,...,0.099059,-0.023477,0.272347,0.241751,0.195054,0.319371,0.082246,0.177846,0.096638,0.002733
10 Things I Hate About You (1999),0.143482,0.273989,-0.005799,1.000000,0.244670,0.223481,0.211473,0.109729,0.011784,0.091964,...,0.104858,0.132460,0.091853,0.158637,0.281934,0.050031,0.088391,0.121029,0.130813,0.110612
"10,000 BC (2008)",0.011998,0.193960,0.112396,0.244670,1.000000,0.234459,0.119132,0.086195,0.059187,-0.025882,...,0.087592,0.094913,0.184521,0.242299,0.240231,0.094773,0.074425,0.088045,0.203002,0.083518

List of 10 movies that are the most similar to 'Harry Potter and the Goblet of Fire (2005)'!

In [17]:
movieLiked = 'Harry Potter and the Goblet of Fire (2005)'
similarityScores = df_similarity[movieLiked]
similarityScores.sort_values(ascending=False)[1:10] # Display 10 most similar movies

title
Harry Potter and the Order of the Phoenix (2007)                                                  0.737753
Harry Potter and the Prisoner of Azkaban (2004)                                                   0.715087
Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)    0.685686
Harry Potter and the Chamber of Secrets (2002)                                                    0.673761
Harry Potter and the Deathly Hallows: Part 1 (2010)                                               0.615772
Harry Potter and the Half-Blood Prince (2009)                                                     0.610858
Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The (2005)                            0.599818
Pirates of the Caribbean: Dead Man's Chest (2006)                                                 0.574820
Charlie and the Chocolate Factory (2005)                                                          0.541193
Name: Harry Potter and the Goblet of Fire (2005), dtype: float64